### ISSUE TITLE
rmt deletes all files when backing up a cluster

### ISSUE THREAD

**Issue by max06** [vipshop/redis-migrate-tool#14]
When I run the redis-migrate-tool with a redis cluster as source and rdb file as target, to perform a full backup of the cluster, it seems to work in the first place.

I can see 100 dump files (have 100 masters) and `INFO` says

# Group
source_nodes_count:100
target_nodes_count:0

# Stats
all_rdb_received:1
all_rdb_parsed:0
all_aof_loaded:0
rdb_received_count:100
rdb_parsed_count:0
aof_loaded_count:0
total_msgs_recv:0
total_msgs_sent:0
total_net_input_bytes:7693531722
total_net_output_bytes:0
total_net_input_bytes_human:7.17G
total_net_output_bytes_human:0B
total_mbufs_inqueue:0
total_msgs_outqueue:0

But when I shutdown the rmt with  the `shutdown` command, all files disappear again. This does not happen when I use `shutdown asap` instead.

**Comment by deep011** [comment]
Thank you very much!
This bug was fixed at this code [commit](https://github.com/vipshop/redis-migrate-tool/commit/3e1abc2899c170b3149452039334f3515dcf39f0), you can try it again.

**Comment by max06** [comment]
Works, thank you for that real quick response on this!
