### ISSUE TITLE
.ibtoolize: AC_CONFIG_MACRO_DIR([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4

### ISSUE THREAD

**Issue by zhenghz** [vipshop/redis-migrate-tool#19]
$autoreconf -fvi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
.ibtoolize: AC_CONFIG_MACRO_DIR([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4
autoreconf: libtoolize failed with exit status: 1

**Comment by deep011** [comment]
把Makefile.am文件中的 “ACLOCAL_AMFLAGS = -I m4” 行删掉试试

**Comment by zhenghz** [comment]
删掉这行后，./configure 最后出现：
.infig.status: error: cannot find input file: Makefile，不知道为啥，config.log改名为 config.txt，求指教。
[config.txt](https://github.com/vipshop/redis-migrate-tool/files/1129759/config.txt)

**Comment by deep011** [comment]
autoreconf这个命令执行成功了吗

**Comment by zhenghz** [comment]
autoreconf -fvi 
有一句提示：src/Makefile.am:34: whitespace following trailing backslash
我这行最后的\t改成空格了。

执行后显示内容如下：
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'

**Comment by zhenghz** [comment]
autoreconf截图：
![Uploading autoreconf截图001.png…]()

**Comment by deep011** [comment]
那你看有Makefile文件吗？

**Comment by zhenghz** [comment]
用zip 下载的安装没报这些错误，很顺利
