### ISSUE TITLE
集群同步目标集群bgsave时子进程目录

### ISSUE THREAD

**Issue by tianyangyang427** [vipshop/redis-migrate-tool#23]
用这个在进行集群数据迁移时，目标集群bgsave fork子进程后，目标集群的dir路径跟随变化，不按conf文件中配置的来。

**Comment by deep011** [comment]
你的配置文件贴一下

**Comment by tianyangyang427** [comment]
[source]
type: redis cluster
dir:/data/redis
servers:
-172.16.137.196:6479
-172.16.137.197:6479
-172.16.137.198:6479
-172.16.137.199:6479

[target]
type: redis cluster
dir:/data/redis
servers :
-10.14.16.110:6379
-10.14.16.111:6379
-10.14.16.112:6379
-10.14.16.113:6379

[common]
listen: 0.0.0.0:8899

上面是迁移工具配置文件.下面是目标集群获取的配置文件

通过: config get dir 获取目标集群路径为:/data/redis

当目标集群出现bgsave时，目标集群的路径变为/root/.ssh目录

**Comment by deep011** [comment]
rmt的配置文件dir选项是配置到common里的

**Comment by tianyangyang427** [comment]
@deep011 谢了，是我这边疏忽了
