### ISSUE TITLE
集群密码存在#号会出现密码错误异常

### ISSUE THREAD

**Issue by wuisme** [vipshop/redis-migrate-tool#33]
在目标密码中写入#的情况下，永远读不到#后边的内容，导致同步不成功。

**Comment by wuisme** [comment]
不太懂c所以直接把密码写入到文件中了，这个只是数据导入一次使用的可以这样做，修改文件为rmt_core.c
371行添加 trgroup->password="自己的密码";  自己测试在单节点到单节点的过程中没有问题。。。。一只java狗的临时解决方案，还请各位尝试。。。或者指点下c读取。。。

**Comment by wuisme** [comment]
最新临时解决方案，注释掉rmt_conf.c中第888行到910行的代码，但是要求rmt.conf中不能有注释了，还请知晓。

**Comment by xulianggg** [comment]
请教下，密码在配置文件中如何设置，能给个配置文件模板吗？
