### ISSUE TITLE
This tools can only migrate database 0 ?

### ISSUE THREAD

**Issue by vnoder** [vipshop/redis-migrate-tool#40]
insert some value into source db 6, but it is migrated to target db 0
Platform: Debian 8
Source Redis Server Version: 2.8.19
Target Redis Server Version: 2.8.9

**Comment by lidezheng** [comment]
Edit file rmt_core.c line 426, add this two lines.

```
log_stdout("---------> write select command to target");
rmt_send_sync_cmd_read_line(tc->sd, "SELECT", "10", NULL);   // the target redis db
```

then make again.  可以指定迁移地址的db号
(但是会将源IP上所有db的key迁移到目标地址中)。

**Comment by vnoder** [comment]
@lidezheng Thanks

**Comment by yaoxiayu** [comment]
没有用啊!

**Comment by yaoxiayu** [comment]
是我哪儿有问题吗?
