### ISSUE TITLE
Support for MULTI/EXEC

### ISSUE THREAD

**Issue by alessandrobologna** [vipshop/redis-migrate-tool#6]
Hi,
running a migration task I see a lot of messages in the logs like the following:
rmt_redis.c:3143 ERROR: parsed unsupported command 'MULTI' 
followed by an hex dump of the commands and data.
Are the transaction commands (http://redis.io/topics/transactions) not supported?
Thanks!

**Comment by therelaxist** [comment]
Are you using twemproxy? Then no.

**Comment by alessandrobologna** [comment]
Thank you, but it doesn't have anything to do with using twemproxy. Digging in the code those commands are simply unknown. I have added logic in my fork to simply skip them

**Comment by ji123vj** [comment]
hi therelaxist,
     I have same problem, how to skip this problem?(rmt_redis.c:3143 ERROR: parsed unsupported command 'MULTI'). thanks!!

**Comment by deep011** [comment]
This issue was fixed.
See the commit: [https://github.com/vipshop/redis-migrate-tool/commit/b52289c837f535b2b10471fb6874e559852b159f](url)
