### ISSUE TITLE
autoreconf -fvi failed

### ISSUE THREAD

**Issue by andyli029** [vipshop/redis-migrate-tool#7]
`configure.ac:8: error: Autoconf version 2.64 or higher is required`

autoconf in centos6.5 is 2.63
```
#rpm -qa |grep autoconf
autoconf-2.63-5.1.el6.noarch
```
updating autoconf is easy，but 2.63 can work, please change，otherwize you have reason.

**Comment by andyli029** [comment]
fixed #8

**Comment by deep011** [comment]
Good job!
