### ISSUE TITLE
从twemproxy 到 新的twemproxy, 同步完成后新集群的大小比原来小很多

### ISSUE THREAD

**Issue by xishian** [vipshop/redis-migrate-tool#78]
源集群有24个节点，每个20G，redis版本3.0.8，总共使用217G
目标集群也是24个节点，每个20G，redis版本5.0.3，同步完以后只有123G

同步过程没有任何异常，虽然目标集群的内存随着时间在往上涨，但是非常缓慢

使用redis_check检查，不一致的key占万分之3.82

**Comment by wyl9527** [comment]
你的解决了么？自己测试没问题，一到大数据量的时候就出现这个现象
